Repository coool-developers/hot-item-collector, pull requests merged in 2024-08, with the labels that each got.

#78 Feat/#76
  frontend/src/components/CategoryItemPage.vue
  frontend/src/components/DetailProductPage.vue
  frontend/src/components/FollowItemPage.vue
  frontend/src/components/LikeItemPage.vue
  frontend/src/components/MainPage.vue
  frontend/src/components/MyProfilePage.vue
  frontend/src/components/NewItemPage.vue
  frontend/src/components/OtherProfilePage.vue
  frontend/src/components/ProductUpdate.vue
  frontend/src/components/SaleProductPage.vue
  frontend/src/components/SearchPage.vue
  src/main/java/com/sparta/hotitemcollector/domain/like/LikeController.java
  src/main/java/com/sparta/hotitemcollector/domain/like/LikeService.java
  src/main/java/com/sparta/hotitemcollector/domain/product/controller/ProductController.java
  src/main/java/com/sparta/hotitemcollector/domain/product/service/ProductService.java
  src/main/java/com/sparta/hotitemcollector/domain/product/service/SearchService.java
Labels: feature, refactor

#83 Feat/#82
  build.gradle
  frontend/src/components/AppHeader.vue
  frontend/src/components/CartPage.vue
  frontend/src/components/CategoryItemPage.vue
  frontend/src/components/ConfirmPassword.vue
  frontend/src/components/DetailOrder.vue
  frontend/src/components/DetailProductPage.vue
  frontend/src/components/EditProduct.vue
  frontend/src/components/FollowItemPage.vue
  frontend/src/components/FollowList.vue
  frontend/src/components/LikeItemPage.vue
  frontend/src/components/MainPage.vue
  frontend/src/components/ManageOrder.vue
  frontend/src/components/MyProfilePage.vue
  frontend/src/components/NewItemPage.vue
  frontend/src/components/OrderItem.vue
  frontend/src/components/OrderPage.vue
  frontend/src/components/OtherProfilePage.vue
  frontend/src/components/ProductUpdate.vue
  frontend/src/components/ProfileUpdate.vue
  frontend/src/components/SaleProductPage.vue
  frontend/src/components/SearchPage.vue
  frontend/src/components/UploadProduct.vue
  frontend/src/main.js
  frontend/vue.config.js
  src/main/java/com/sparta/hotitemcollector/global/config/RedisConfig.java
  src/main/java/com/sparta/hotitemcollector/global/config/SecurityConfig.java
  src/main/java/com/sparta/hotitemcollector/global/config/WebConfig.java
  src/main/java/com/sparta/hotitemcollector/global/jwt/JwtAuthenticationFilter.java
Labels: fix, refactor

#85 Refactor/#77
  docker-compose.yml
  frontend/src/components/OrderItem.vue
  frontend/src/main.js
  src/main/java/com/sparta/hotitemcollector/domain/cart/CartItem.java
  src/main/java/com/sparta/hotitemcollector/domain/cart/CartService.java
  src/main/java/com/sparta/hotitemcollector/domain/follow/Follow.java
  src/main/java/com/sparta/hotitemcollector/domain/like/Likes.java
  src/main/java/com/sparta/hotitemcollector/domain/order/OrderService.java
  src/main/java/com/sparta/hotitemcollector/domain/order/Orders.java
  src/main/java/com/sparta/hotitemcollector/domain/orderitem/OrderItem.java
  src/main/java/com/sparta/hotitemcollector/domain/orderitem/OrderItemRepository.java
  src/main/java/com/sparta/hotitemcollector/domain/payment/Payment.java
  src/main/java/com/sparta/hotitemcollector/domain/product/entity/Product.java
  src/main/java/com/sparta/hotitemcollector/domain/s3/service/S3Service.java
  src/main/java/com/sparta/hotitemcollector/domain/token/Token.java
  src/main/java/com/sparta/hotitemcollector/domain/user/ProfileImage.java
  src/main/java/com/sparta/hotitemcollector/domain/user/User.java
  src/main/java/com/sparta/hotitemcollector/domain/user/UserRepository.java
  src/main/java/com/sparta/hotitemcollector/global/config/WebConfig.java
  src/main/resources/application.yml
  src/test/java/com/sparta/hotitemcollector/TestConfig.java
  src/test/java/com/sparta/hotitemcollector/domain/cartitem/CartItemRepositoryTest.java
  src/test/java/com/sparta/hotitemcollector/domain/follow/FollowRepositoryTest.java
  src/test/java/com/sparta/hotitemcollector/domain/like/LikeRepositoryTest.java
  src/test/java/com/sparta/hotitemcollector/domain/order/OrderRepositoryTest.java
  src/test/java/com/sparta/hotitemcollector/domain/orderitem/OrderItemRepositoryTest.java
  src/test/java/com/sparta/hotitemcollector/domain/payment/PaymentRepositoryTest.java
  src/test/java/com/sparta/hotitemcollector/domain/product/ProductRepositoryTest.java
  src/test/java/com/sparta/hotitemcollector/domain/token/TokenRepositoryTest.java
  src/test/java/com/sparta/hotitemcollector/domain/user/UserRepositoryTest.java
Labels: refactor

#90 Feat/#86
  build.gradle
  src/main/generated/com/sparta/hotitemcollector/domain/cart/QCartItem.java
  src/main/generated/com/sparta/hotitemcollector/domain/follow/QFollow.java
  src/main/generated/com/sparta/hotitemcollector/domain/like/QLikes.java
  src/main/generated/com/sparta/hotitemcollector/domain/order/QOrders.java
  src/main/generated/com/sparta/hotitemcollector/domain/orderitem/QOrderItem.java
  src/main/generated/com/sparta/hotitemcollector/domain/payment/QPayment.java
  src/main/generated/com/sparta/hotitemcollector/domain/product/entity/QProduct.java
  src/main/generated/com/sparta/hotitemcollector/domain/product/entity/QProductImage.java
  src/main/generated/com/sparta/hotitemcollector/domain/token/QToken.java
  src/main/generated/com/sparta/hotitemcollector/domain/user/QProfileImage.java
  src/main/generated/com/sparta/hotitemcollector/domain/user/QUser.java
  src/main/generated/com/sparta/hotitemcollector/global/QTimestamped.java
  src/main/java/com/sparta/hotitemcollector/domain/order/OrderService.java
  src/main/java/com/sparta/hotitemcollector/domain/orderitem/OrderItemRepository.java
  src/main/java/com/sparta/hotitemcollector/domain/orderitem/OrderItemRepositoryCustom.java
  src/main/java/com/sparta/hotitemcollector/domain/orderitem/OrderItemRepositoryImpl.java
  src/main/java/com/sparta/hotitemcollector/domain/product/entity/ProductImage.java
  src/main/java/com/sparta/hotitemcollector/domain/product/repository/ProductRepository.java
  src/main/java/com/sparta/hotitemcollector/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/com/sparta/hotitemcollector/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/sparta/hotitemcollector/domain/product/service/ProductService.java
  src/main/java/com/sparta/hotitemcollector/domain/product/service/SearchService.java
  src/main/java/com/sparta/hotitemcollector/domain/user/UserService.java
  src/main/java/com/sparta/hotitemcollector/global/config/JPAConfig.java
  src/test/java/com/sparta/hotitemcollector/TestConfig.java
  src/test/java/com/sparta/hotitemcollector/domain/orderitem/OrderItemRepositoryTest.java
  src/test/java/com/sparta/hotitemcollector/domain/product/ProductRepositoryTest.java
Labels: feature

#121 Refactor/#96
  frontend/src/components/DetailProductPage.vue
  src/main/generated/com/sparta/hotitemcollector/domain/user/QProfileImage.java
  src/main/generated/com/sparta/hotitemcollector/domain/user/QUser.java
  src/main/java/com/sparta/hotitemcollector/domain/product/dto/HotProductResponseDto.java
  src/main/java/com/sparta/hotitemcollector/domain/product/dto/ProductImageResponseDto.java
  src/main/java/com/sparta/hotitemcollector/domain/product/dto/ProductResponseDto.java
  src/main/java/com/sparta/hotitemcollector/domain/product/dto/ProductSimpleResponseDto.java
  src/main/java/com/sparta/hotitemcollector/domain/product/entity/ProductImage.java
  src/main/java/com/sparta/hotitemcollector/domain/product/repository/ProductRepository.java
  src/main/java/com/sparta/hotitemcollector/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/com/sparta/hotitemcollector/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/sparta/hotitemcollector/domain/product/service/ProductService.java
  src/main/java/com/sparta/hotitemcollector/domain/product/service/SearchService.java
  src/main/java/com/sparta/hotitemcollector/domain/user/ProfileImage.java
  src/main/java/com/sparta/hotitemcollector/domain/user/User.java
  src/main/java/com/sparta/hotitemcollector/domain/user/UserRepository.java
  src/main/java/com/sparta/hotitemcollector/domain/user/UserService.java
  src/main/java/com/sparta/hotitemcollector/domain/user/dto/user/ProfileImageResponseDto.java
  src/test/java/com/sparta/hotitemcollector/domain/product/ProductRepositoryTest.java
Labels: refactor

#130 Feat/#125
  frontend/src/client.js
  frontend/src/components/AppHeader.vue
  frontend/src/components/OAuthSignupPage.vue
  frontend/src/main.js
  frontend/vue.config.js
  src/main/java/com/sparta/hotitemcollector/domain/user/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/sparta/hotitemcollector/global/config/WebConfig.java
  src/main/resources/newtestpay.html
  src/main/resources/templates/OAuthSignupPage.html
  src/main/resources/templates/완완 개인정보수정비번확인.html
  src/main/resources/templates/완완 개인정보수정페이지.html
  src/main/resources/templates/완완 검색결과화면.html
  src/main/resources/templates/완완 구매한 상품 목록.html
  src/main/resources/templates/완완 마이페이지.html
  src/main/resources/templates/완완 메인페이지.html
  src/main/resources/templates/완완 상품 상세보기.html
  src/main/resources/templates/완완 상품등록페이지.html
  src/main/resources/templates/완완 상품등록확인페이지.html
  src/main/resources/templates/완완 유저프로필.html
  src/main/resources/templates/완완 장바구니페이지.html
  src/main/resources/templates/완완 주문결제페이지.html
  src/main/resources/templates/완완 주문관리페이지.html
  src/main/resources/templates/완완 주문상품확인페이지.html
  src/main/resources/templates/완완 판매상품 목록 .html
  src/main/resources/templates/완완 팔로워리스트페이지.html
  src/main/resources/templates/채팅화면.html
  src/main/resources/testcancel.html
  src/main/resources/testpay.html
  src/main/resources/testsocket_user1.html
  src/main/resources/testsocket_user2.html
Labels: refactor

#133 Feat/#72
  src/main/java/com/sparta/hotitemcollector/domain/user/UserRepository.java
  src/main/java/com/sparta/hotitemcollector/domain/user/UserService.java
  src/main/java/com/sparta/hotitemcollector/domain/user/dto/auth/SignupRequestDto.java
  src/main/java/com/sparta/hotitemcollector/domain/user/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/sparta/hotitemcollector/domain/user/oauthUser/OAuthUserRepository.java
  src/main/java/com/sparta/hotitemcollector/global/email/EmailService.java
  src/main/java/com/sparta/hotitemcollector/global/exception/ErrorCode.java
  src/main/resources/application.yml
Labels: fix

#175 Feat/#174
  README.md
Labels: feature
