Repository coool-developers/hot-item-collector, pull requests merged in 2024-07, with the labels that each got.

#2 [#1] ✨ feat : 좋아요 생성 구현
  src/main/java/com/sparta/hotitemcollector/domain/like/LikeController.java
  src/main/java/com/sparta/hotitemcollector/domain/like/LikeRepository.java
  src/main/java/com/sparta/hotitemcollector/domain/like/LikeService.java
  src/main/java/com/sparta/hotitemcollector/global/exception/ErrorCode.java
Labels: feature

#9 [Feat] 상품 CRUD
  src/main/java/com/sparta/hotitemcollector/domain/product/Product.java
  src/main/java/com/sparta/hotitemcollector/domain/product/ProductCategory.java
  src/main/java/com/sparta/hotitemcollector/domain/product/ProductController.java
  src/main/java/com/sparta/hotitemcollector/domain/product/ProductRequestDto.java
  src/main/java/com/sparta/hotitemcollector/domain/product/ProductResponseDto.java
  src/main/java/com/sparta/hotitemcollector/domain/product/ProductService.java
  src/main/java/com/sparta/hotitemcollector/domain/product/ProductStatus.java
  src/main/java/com/sparta/hotitemcollector/global/exception/ErrorCode.java
Labels: feature

#13 [Feat] 장바구니 CRUD
  src/main/java/com/sparta/hotitemcollector/domain/cart/Cart.java
  src/main/java/com/sparta/hotitemcollector/domain/cart/CartController.java
  src/main/java/com/sparta/hotitemcollector/domain/cart/CartItem.java
  src/main/java/com/sparta/hotitemcollector/domain/cart/CartItemRepository.java
  src/main/java/com/sparta/hotitemcollector/domain/cart/CartRepository.java
  src/main/java/com/sparta/hotitemcollector/domain/cart/CartService.java
  src/main/java/com/sparta/hotitemcollector/domain/cart/dto/CartItemResponseDto.java
  src/main/java/com/sparta/hotitemcollector/domain/cartitem/CartItem.java
  src/main/java/com/sparta/hotitemcollector/domain/cartitem/CartItemRepository.java
  src/main/java/com/sparta/hotitemcollector/global/exception/ErrorCode.java
Labels: feature

#15 Feat/#8
  build.gradle
  docker-compose.yml
  src/main/java/com/sparta/hotitemcollector/domain/security/UserDetailsImpl.java
  src/main/java/com/sparta/hotitemcollector/domain/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/hotitemcollector/domain/token/Token.java
  src/main/java/com/sparta/hotitemcollector/domain/token/TokenRepository.java
  src/main/java/com/sparta/hotitemcollector/domain/token/TokenService.java
  src/main/java/com/sparta/hotitemcollector/domain/user/User.java
  src/main/java/com/sparta/hotitemcollector/domain/user/UserRepository.java
  src/main/java/com/sparta/hotitemcollector/domain/user/UserService.java
  src/main/java/com/sparta/hotitemcollector/domain/user/controller/AuthController.java
  src/main/java/com/sparta/hotitemcollector/domain/user/dto/LoginReqeustDto.java
  src/main/java/com/sparta/hotitemcollector/domain/user/dto/LoginResponseDto.java
  src/main/java/com/sparta/hotitemcollector/domain/user/dto/SignupRequestDto.java
  src/main/java/com/sparta/hotitemcollector/global/config/RedisConfig.java
  src/main/java/com/sparta/hotitemcollector/global/config/SecurityConfig.java
  src/main/java/com/sparta/hotitemcollector/global/exception/ErrorCode.java
  src/main/java/com/sparta/hotitemcollector/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/hotitemcollector/global/jwt/JwtUtil.java
  src/main/java/com/sparta/hotitemcollector/global/jwt/RedisUtil.java
  src/main/resources/application.yml
Labels: feature

#16 Feat/#8 ErrorCode 추가
  src/main/java/com/sparta/hotitemcollector/global/exception/ErrorCode.java
  src/main/resources/application.yml
Labels: fix

#21 [ Feat ] 상품 검색
  src/main/java/com/sparta/hotitemcollector/domain/product/ProductController.java
  src/main/java/com/sparta/hotitemcollector/domain/product/ProductRepository.java
  src/main/java/com/sparta/hotitemcollector/domain/product/ProductService.java
  src/main/java/com/sparta/hotitemcollector/domain/product/SearchService.java
Labels: feature

#24 [Fix] Cart 테이블 삭제
  src/main/java/com/sparta/hotitemcollector/domain/cart/Cart.java
  src/main/java/com/sparta/hotitemcollector/domain/cart/CartItem.java
  src/main/java/com/sparta/hotitemcollector/domain/cart/CartItemRepository.java
  src/main/java/com/sparta/hotitemcollector/domain/cart/CartRepository.java
  src/main/java/com/sparta/hotitemcollector/domain/cart/CartService.java
  src/main/java/com/sparta/hotitemcollector/domain/cart/dto/CartItemResponseDto.java
  src/main/java/com/sparta/hotitemcollector/domain/user/UserService.java
  src/main/java/com/sparta/hotitemcollector/global/exception/ErrorCode.java
Labels: fix

#27 Feat/#14
  src/main/java/com/sparta/hotitemcollector/domain/cart/CartController.java
  src/main/java/com/sparta/hotitemcollector/domain/cart/CartItemRepository.java
  src/main/java/com/sparta/hotitemcollector/domain/cart/CartService.java
  src/main/java/com/sparta/hotitemcollector/domain/cart/dto/CartItemResponseDto.java
  src/main/java/com/sparta/hotitemcollector/domain/order/OrderController.java
  src/main/java/com/sparta/hotitemcollector/domain/order/OrderRepository.java
  src/main/java/com/sparta/hotitemcollector/domain/order/OrderService.java
  src/main/java/com/sparta/hotitemcollector/domain/order/Orders.java
  src/main/java/com/sparta/hotitemcollector/domain/order/dto/OrderItemBySellerResponseDto.java
  src/main/java/com/sparta/hotitemcollector/domain/order/dto/OrderItemResponseDto.java
  src/main/java/com/sparta/hotitemcollector/domain/order/dto/OrderRequestDto.java
  src/main/java/com/sparta/hotitemcollector/domain/order/dto/OrderResponseDto.java
  src/main/java/com/sparta/hotitemcollector/domain/order/dto/OrderStatusRequestDto.java
  src/main/java/com/sparta/hotitemcollector/domain/orderitem/OrderItem.java
  src/main/java/com/sparta/hotitemcollector/domain/orderitem/OrderItemRepository.java
  src/main/java/com/sparta/hotitemcollector/global/exception/ErrorCode.java
Labels: feature

#28 [ Feat ] S3 상품 이미지 업로드
  build.gradle
  src/main/java/com/sparta/hotitemcollector/domain/cart/CartItem.java
  src/main/java/com/sparta/hotitemcollector/domain/cart/CartService.java
  src/main/java/com/sparta/hotitemcollector/domain/cart/dto/CartItemResponseDto.java
  src/main/java/com/sparta/hotitemcollector/domain/like/LikeController.java
  src/main/java/com/sparta/hotitemcollector/domain/like/LikeService.java
  src/main/java/com/sparta/hotitemcollector/domain/like/Likes.java
  src/main/java/com/sparta/hotitemcollector/domain/order/OrderService.java
  src/main/java/com/sparta/hotitemcollector/domain/order/dto/OrderItemBySellerResponseDto.java
  src/main/java/com/sparta/hotitemcollector/domain/order/dto/OrderItemResponseDto.java
  src/main/java/com/sparta/hotitemcollector/domain/orderitem/OrderItem.java
  src/main/java/com/sparta/hotitemcollector/domain/orderitem/OrderItemRepository.java
  src/main/java/com/sparta/hotitemcollector/domain/product/controller/ProductController.java
  src/main/java/com/sparta/hotitemcollector/domain/product/dto/HotProductResponseDto.java
  src/main/java/com/sparta/hotitemcollector/domain/product/dto/ProductImageRequestDto.java
  src/main/java/com/sparta/hotitemcollector/domain/product/dto/ProductImageResponseDto.java
  src/main/java/com/sparta/hotitemcollector/domain/product/dto/ProductRequestDto.java
  src/main/java/com/sparta/hotitemcollector/domain/product/dto/ProductResponseDto.java
  src/main/java/com/sparta/hotitemcollector/domain/product/dto/ProductSimpleResponseDto.java
  src/main/java/com/sparta/hotitemcollector/domain/product/entity/Product.java
  src/main/java/com/sparta/hotitemcollector/domain/product/entity/ProductCategory.java
  src/main/java/com/sparta/hotitemcollector/domain/product/entity/ProductImage.java
  src/main/java/com/sparta/hotitemcollector/domain/product/entity/ProductStatus.java
  src/main/java/com/sparta/hotitemcollector/domain/product/repository/ProductImageRepository.java
  src/main/java/com/sparta/hotitemcollector/domain/product/repository/ProductRepository.java
  src/main/java/com/sparta/hotitemcollector/domain/product/service/ProductImageService.java
  src/main/java/com/sparta/hotitemcollector/domain/product/service/ProductService.java
  src/main/java/com/sparta/hotitemcollector/domain/product/service/SearchService.java
  src/main/java/com/sparta/hotitemcollector/domain/s3/config/S3Config.java
  src/main/java/com/sparta/hotitemcollector/domain/s3/service/S3Service.java
  src/main/java/com/sparta/hotitemcollector/global/exception/ErrorCode.java
  src/main/resources/application.yml
Labels: feature

#31 Refactor/#30 Follow부분 코드 수정
  http/팔로우.http
  src/main/java/com/sparta/hotitemcollector/domain/follow/Follow.java
  src/main/java/com/sparta/hotitemcollector/domain/follow/FollowRepository.java
  src/main/java/com/sparta/hotitemcollector/domain/follow/FollowService.java
  src/main/java/com/sparta/hotitemcollector/domain/user/UserService.java
  src/main/java/com/sparta/hotitemcollector/global/exception/ErrorCode.java
Labels: refactor

#33 Feat/#32
  src/main/java/com/sparta/hotitemcollector/domain/cart/CartController.java
  src/main/java/com/sparta/hotitemcollector/domain/cart/CartService.java
  src/main/java/com/sparta/hotitemcollector/domain/order/OrderController.java
  src/main/java/com/sparta/hotitemcollector/domain/order/OrderRepository.java
  src/main/java/com/sparta/hotitemcollector/domain/order/OrderService.java
  src/main/java/com/sparta/hotitemcollector/domain/orderitem/OrderItemRepository.java
Labels: fix

#41 [#40] ✨ feat : 프론트엔드 화면 생성
  src/main/resources/templates/완 개인정보수정비번확인.html
  src/main/resources/templates/완 개인정보수정페이지.html
  src/main/resources/templates/완 검색결과화면.html
  src/main/resources/templates/완 구매한 상품 목록.html
  src/main/resources/templates/완 마이페이지.html
  src/main/resources/templates/완 메인페이지.html
  src/main/resources/templates/완 상품 상세보기.html
  src/main/resources/templates/완 상품등록확인페이지.html
  src/main/resources/templates/완 유저프로필.html
  src/main/resources/templates/완 장바구니페이지.html
  src/main/resources/templates/완 주문결제페이지.html
  src/main/resources/templates/완 주문관리페이지.html
  src/main/resources/templates/완 주문상품확인페이지.html
  src/main/resources/templates/완 팔로워리스트페이지.html
Labels: feature

#43 Refactor/#39
  src/main/java/com/sparta/hotitemcollector/domain/cart/CartItemRepository.java
  src/main/java/com/sparta/hotitemcollector/domain/cart/CartService.java
  src/main/java/com/sparta/hotitemcollector/domain/follow/GetAllFollowsResponseDto.java
  src/main/java/com/sparta/hotitemcollector/domain/order/OrderController.java
  src/main/java/com/sparta/hotitemcollector/domain/order/OrderService.java
  src/main/java/com/sparta/hotitemcollector/domain/payment/PaymentService.java
Labels: refactor

#50 Feat/#47
  frontend/src/components/CartPage.vue
  frontend/src/components/OrderPage.vue
  src/main/java/com/sparta/hotitemcollector/domain/cart/dto/CartItemResponseDto.java
  src/main/java/com/sparta/hotitemcollector/domain/order/OrderController.java
  src/main/java/com/sparta/hotitemcollector/domain/order/dto/OrderItemBySellerResponseDto.java
  src/main/java/com/sparta/hotitemcollector/domain/order/dto/OrderRequestDto.java
Labels: feature

#52 Feat/#40
  frontend/src/assets/user.png
  frontend/src/components/AppFooter.vue
  frontend/src/components/AppHeader.vue
  frontend/src/components/ConfirmPassword.vue
  frontend/src/components/MainPage.vue
  frontend/src/components/ManageOrder.vue
  frontend/src/components/MyProfilePage.vue
  frontend/src/components/OrderItem.vue
  frontend/src/components/OrderPage.vue
  frontend/src/components/OtherProfilePage.vue
  frontend/src/components/ProductUpdate.vue
  frontend/src/components/ProfileUpdate.vue
  frontend/src/components/SaleProductPage.vue
  frontend/src/components/SearchPage.vue
  frontend/src/components/UploadProduct.vue
  frontend/src/router/index.js
  src/main/java/com/sparta/hotitemcollector/domain/user/UserController.java
  src/main/java/com/sparta/hotitemcollector/domain/user/UserService.java
  src/main/java/com/sparta/hotitemcollector/domain/user/dto/user/ConfirmPasswordDto.java
  src/main/java/com/sparta/hotitemcollector/domain/user/dto/user/GetMyProfileDto.java
  src/main/java/com/sparta/hotitemcollector/domain/user/dto/user/GetUserProfileDto.java
  src/main/java/com/sparta/hotitemcollector/global/config/WebConfig.java
  src/main/java/com/sparta/hotitemcollector/global/jwt/JwtAuthenticationFilter.java
Labels: feature

#55 Feat/#53
  frontend/src/components/AppHeader.vue
  frontend/src/components/CartPage.vue
  frontend/src/components/ManageOrder.vue
  frontend/src/router/index.js
  src/main/java/com/sparta/hotitemcollector/domain/order/OrderController.java
  src/main/java/com/sparta/hotitemcollector/domain/order/OrderService.java
  src/main/java/com/sparta/hotitemcollector/domain/order/OrderStatus.java
  src/main/java/com/sparta/hotitemcollector/domain/order/dto/OrderStatusRequestDto.java
  src/main/java/com/sparta/hotitemcollector/global/exception/ErrorCode.java
Labels: feature

#63 Feat/#59 주문 상세 페이지 연동
  frontend/src/components/DetailOrder.vue
  frontend/src/components/OrderPage.vue
  src/main/java/com/sparta/hotitemcollector/domain/order/OrderController.java
  src/main/java/com/sparta/hotitemcollector/domain/order/OrderService.java
  src/main/java/com/sparta/hotitemcollector/domain/order/OrderStatus.java
  src/main/java/com/sparta/hotitemcollector/domain/payment/PaymentService.java
Labels: feature

#66 Feat/#61
  frontend/src/components/DetailProductPage.vue
  frontend/src/components/ManageOrder.vue
  frontend/src/components/OrderItem.vue
  frontend/src/components/OrderPage.vue
  src/main/java/com/sparta/hotitemcollector/domain/follow/FollowController.java
  src/main/java/com/sparta/hotitemcollector/domain/follow/FollowService.java
  src/main/java/com/sparta/hotitemcollector/domain/follow/UserFollowResponseDto.java
  src/main/java/com/sparta/hotitemcollector/domain/like/LikeController.java
  src/main/java/com/sparta/hotitemcollector/domain/like/LikeService.java
  src/main/java/com/sparta/hotitemcollector/domain/like/UserLikeResponseDto.java
  src/main/java/com/sparta/hotitemcollector/domain/payment/PaymentService.java
  src/main/java/com/sparta/hotitemcollector/domain/payment/dto/OrderPrepareRequestDto.java
Labels: feature

#70 Feat/#67
  frontend/src/components/AppHeader.vue
  frontend/src/components/MyProfilePage.vue
  frontend/src/components/OtherProfilePage.vue
  frontend/src/components/SaleProductPage.vue
  src/main/java/com/sparta/hotitemcollector/domain/follow/FollowRepository.java
  src/main/java/com/sparta/hotitemcollector/domain/user/ProfileImage.java
  src/main/java/com/sparta/hotitemcollector/domain/user/UserService.java
  src/main/java/com/sparta/hotitemcollector/domain/user/dto/user/GetMyProfileDto.java
  src/main/java/com/sparta/hotitemcollector/domain/user/dto/user/GetUserProfileDto.java
Labels: feature, refactor

#74 Fix/#71
  frontend/src/components/DetailProductPage.vue
  src/main/java/com/sparta/hotitemcollector/domain/payment/PaymentService.java
Labels: fix
